mode: auto

banner:
  enable: true
  title: 逆水行舟不进则退
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
    # _config.yun.yml
  medium_zoom: true
bg_image:
  enable: true
  url: /images/1.png
  dark: /images/55.png
  blur: 10px # 设置背景模糊程度
  opacity: 0.6
avatar:
  enable: true
  url: "/images/wgqs.jpg"
  rounded: true
  opacity: 1
  mickey_mouse: false
status:
  enable: true
  emoji: ☺️
  message: 今夕何夕，见此良人
social:
  - name: 番剧网站
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: https://www.jiongciyuan1.cc/ # config.feed.path
    icon: ri:rss-line
    color: orange
  - name: GitHub
    link: https://github.com/web218
    icon: ri:github-line
    color: '#181717'
  - name: 网易邮箱
    link: https://mail.163.com
    icon: ri:mail-line
    color: '#8E71C1'
  # - name: 微博
  #   link: #
  #   icon: ri:weibo-line
  #   color: '#E6162D'
  # - name: 豆瓣
  #   link: #
  #   icon: ri:douban-line
  #   color: '#007722'
  - name: 哔哩哔哩
    link: https://space.bilibili.com/3537106320230948
    icon: ri:bilibili-line
    color: '#FF8EB3'
  # - name: 微信公众号
  #   link: #
  #   icon: ri:wechat-2-line
  #   color: '#1AAD19'
  - name: QQ
    link: https://qm.qq.com/q/3nByicuAkg
    icon: ri:qq-line
    color: '#87CEEB'
pages:
  - name: 我的小伙伴们
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
  # custom:
  #   title: 文档
  #   path: https://yun.yunyoujun.cn
  #   icon: ri:settings-line

fireworks:
  enable: true

scrollreveal:
  enable: true

smoothScroll: true

say:
  enable: true
  api: https://el-bot-api.vercel.app/api/words/young

search:
  modal: true

footer:
  since: 2025
  icon:
    name: ri:heart-3-line
    animated: true
    color: "#ff0000"

vendors:
  yun_markdown_css: star-markdown-css@0.5.3/dist/earth/earth-markdown.min.css
